name: codeclimate ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - run: make build
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          JACOCO_SOURCE_PATH: src/main/java
        with:
          coverageCommand: ./gradlew jacocoTestReport
          coverageLocations: ${{ github.workspace }}build/customJacocoReportDir/test/jacocoTestReport.xml:jacoco
          coverageInputType: jacoco
